---
environment_name: tcross-demo
aws_region : us-east-1
key_name: tcross

zone_domain: demo.testing.ansible.com

vpc_id: vpc-c4e9aea0
vpc_cidr: 10.0.0.0/16

public_subnet_a_cidr: 10.0.0.0/18
public_subnet_b_cidr: 10.0.64.0/18
public_subnet_c_cidr: 10.0.128.0/18

public_subnet_a_az: us-east-1b
public_subnet_b_az: us-east-1c
public_subnet_c_az: us-east-1d

public_subnet_a_id: subnet-02768e28
public_subnet_b_id: subnet-79f1440f
public_subnet_c_id: subnet-7238f42a

amis:
  windows_2012_r2_base: ami-5027053a
  free_bsd_10_2: ami-7389ab19
  rhel_7_2: ami-28a78842
  suse_12: ami-84a689ee
  ubuntu_14_04: ami-b8a689d2

ansible_ssh_user: ansible
kube_service_addresses: 10.254.0.0/16
kube_overlay_ip: 4.0.0.0
kube_overlay_prefix: 16
dns_setup: false
dns_domain: ansikube.local
dns_server: 10.254.0.10
kube_aws_create_etc_hosts: false
kube_aws_cluster_name: ansikube

rhn_username: tcross@redhat.com
rhn_password: "!I__am__6770!"
