---
- name: restart daemons
  command: /bin/true
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler

- name: restart apiserver
  service: name=kube-apiserver state=restarted

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted

- name: restart scheduler
  service: name=kube-scheduler state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: reload systemctl
  shell: systemctl --system daemon-reload
  when: systemd_unit_files | changed
